import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib
matplotlib.rcParams.update({'font.size': 22})

plt.figure(figsize=(10,10))

# The file name should be the raw free energy data generated by free_energy.py
pmf = np.loadtxt('wham_pmf.txt')
x = list(np.unique(pmf[:,1]))
y = list(np.unique(pmf[:,2]))
z = np.ones((len(x), len(y)), np.float32)*100000

for i in pmf:
    z[x.index(i[1]), y.index(i[2])] = i[4]
z[z>10000] = np.inf
x = np.array(x)
y = np.array(y)
plt.contourf(x, y, z.T, 25, cmap=cm.nipy_spectral, alpha=0.5)
plt.xlabel('CV1')
plt.ylabel('CV2')
#plt.title('2D PMF of %s' % pmff)
plt.tight_layout()
plt.show()
